apiVersion: apps/v1
kind: Deployment
metadata:
   name: argo-rollouts
  
   labels:
      type: dep 
spec:
   replicas: 2
   selector:
      matchLabels:
         pod: frontend 
   template:
      metadata:
         labels:
             pod: frontend 
      spec:
         containers:
         - name: frontend 
           image: gcr.io/helm-argo/prom-app
           ports:
           - name: web 
             containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: svc-unmanaged
   labels:
      type: service-frontend
      job: web-frontend-api
  
spec:
    type: LoadBalancer
    ports:
    - targetPort: 8080
      port: 8080
      name: web
    selector:
       pod: frontend
