apiVersion: v1
kind: Secret
metadata:
  name: cluster-us
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster-us
  server: https://us-central1-connectgateway.googleapis.com/v1beta1/projects/768923947441/locations/us-central1/gkeMemberships/us
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }